using PulpMXFantasy.Domain.Abstractions;

namespace PulpMXFantasy.Domain.Entities;

/// <summary>
/// Represents a user's fantasy team for a specific event.
/// </summary>
/// <remarks>
/// WHY TEAM EXISTS:
/// ================
/// Each event requires a new team selection (8 riders: 4 from 250, 4 from 450).
/// Team entity groups the 8 rider selections together with metadata.
///
/// TEAM COMPOSITION RULES:
/// - Exactly 4 riders from 250 class
/// - Exactly 4 riders from 450 class
/// - Exactly 1 All-Star per class (2 total)
/// - Cannot pick same rider from previous event in same series
///
/// TEAM SCORING:
/// Total team score = Sum of all 8 riders' fantasy points
/// Goal: Maximize total points through optimal rider selection
///
/// REAL-WORLD EXAMPLE:
/// User "kyle_pott" creates team for "Anaheim 1":
/// 250 Class: Haiden Deegan (AS), Tom Vialle, Chance Hymas, RJ Hampshire
/// 450 Class: Eli Tomac (AS), Chase Sexton, Jason Anderson, Justin Barcia
///
/// After race:
/// - 250 riders score: 20 + 34 + 28 + 18 = 100 points
/// - 450 riders score: 18 + 50 + 26 + 12 = 106 points
/// - Total team score: 206 points
///
/// MULTIPLAYER COMPETITION:
/// Multiple users create teams for same event, winner has highest total score.
/// Leaderboard ranks teams by total fantasy points.
///
/// ML SYSTEM USAGE:
/// Team optimizer uses ML predictions to select optimal 8 riders
/// respecting all constraints (All-Star requirement, consecutive picks, etc.)
/// </remarks>
public class Team : IHasTimestamps
{
    /// <summary>
    /// Internal unique identifier for the team
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Foreign key to the event this team is for
    /// </summary>
    public required Guid EventId { get; init; }

    /// <summary>
    /// User identifier (username or external auth ID)
    /// </summary>
    /// <remarks>
    /// In future version with authentication, this would be a foreign key
    /// to an AspNetUsers table or similar.
    ///
    /// For now, storing as string to track team ownership without full auth system.
    /// Example: "kyle_pott", "user123", or email address
    /// </remarks>
    public required string UserId { get; init; }

    /// <summary>
    /// Optional team name chosen by user
    /// </summary>
    /// <remarks>
    /// Examples: "Pott's Podium Pickers", "Factory Connection", "Holeshot Heroes"
    /// If null, default to "{Username}'s Team" in UI
    /// </remarks>
    public string? TeamName { get; set; }

    /// <summary>
    /// Total fantasy points scored by this team (sum of all 8 riders)
    /// </summary>
    /// <remarks>
    /// NULL until race completes and all rider fantasy points are calculated.
    ///
    /// Calculation:
    /// TotalPoints = Sum(TeamSelections.Select(ts => ts.EventRider.FantasyPoints))
    ///
    /// Used for:
    /// - Leaderboard ranking
    /// - Comparing team performance
    /// - Tracking accuracy of ML predictions vs actual scores
    /// </remarks>
    public int? TotalPoints { get; set; }

    /// <summary>
    /// Whether this team was generated by the ML optimizer (vs manual user selection)
    /// </summary>
    /// <remarks>
    /// Used to:
    /// - Track ML system performance
    /// - Display "AI-Generated" badge in UI
    /// - Compare ML-generated teams vs human selections
    /// </remarks>
    public bool IsOptimized { get; set; } = false;

    /// <summary>
    /// Timestamp when this team was created
    /// </summary>
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Timestamp of the last update to this team
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Navigation property to the event this team is for
    /// </summary>
    public Event Event { get; init; } = null!;

    /// <summary>
    /// Navigation property to the 8 rider selections on this team
    /// </summary>
    /// <remarks>
    /// ONE team -> EXACTLY 8 team selections (4 from 250, 4 from 450)
    /// Used for:
    /// - Displaying team roster
    /// - Calculating total team score
    /// - Validating team composition rules
    /// </remarks>
    public ICollection<TeamSelection> TeamSelections { get; init; } = new List<TeamSelection>();

    /// <summary>
    /// Calculates and updates the total team score from all rider selections.
    /// </summary>
    /// <remarks>
    /// Call this after the race completes and all EventRider fantasy points are calculated.
    ///
    /// Side effects:
    /// - Sets TotalPoints property
    /// - Updates UpdatedAt timestamp
    ///
    /// Example usage:
    /// <code>
    /// // After race completion
    /// foreach (var eventRider in event.EventRiders)
    /// {
    ///     eventRider.CalculateFantasyPoints();
    /// }
    ///
    /// foreach (var team in teams)
    /// {
    ///     team.CalculateTotalScore();
    /// }
    /// </code>
    /// </remarks>
    public void CalculateTotalScore()
    {
        if (TeamSelections.Count != 8)
        {
            throw new InvalidOperationException(
                $"Team must have exactly 8 riders to calculate score. Current count: {TeamSelections.Count}");
        }

        var allRidersHavePoints = TeamSelections.All(ts => ts.EventRider.FantasyPoints.HasValue);
        if (!allRidersHavePoints)
        {
            throw new InvalidOperationException(
                "Cannot calculate team score - not all riders have fantasy points calculated yet. " +
                "Ensure all EventRider.CalculateFantasyPoints() are called first.");
        }

        TotalPoints = TeamSelections.Sum(ts => ts.EventRider.FantasyPoints!.Value);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Validates that this team meets all composition rules.
    /// </summary>
    /// <returns>True if valid, false otherwise with error messages</returns>
    public (bool IsValid, List<string> Errors) Validate()
    {
        var errors = new List<string>();

        // Rule 1: Exactly 8 riders
        if (TeamSelections.Count != 8)
        {
            errors.Add($"Team must have exactly 8 riders. Current count: {TeamSelections.Count}");
        }

        // Rule 2: Exactly 4 from 250 class
        var count250 = TeamSelections.Count(ts => ts.EventRider.BikeClass == Enums.BikeClass.Class250);
        if (count250 != 4)
        {
            errors.Add($"Team must have exactly 4 riders from 250 class. Current count: {count250}");
        }

        // Rule 3: Exactly 4 from 450 class
        var count450 = TeamSelections.Count(ts => ts.EventRider.BikeClass == Enums.BikeClass.Class450);
        if (count450 != 4)
        {
            errors.Add($"Team must have exactly 4 riders from 450 class. Current count: {count450}");
        }

        // Rule 4: Exactly 1 All-Star per class
        var allStar250Count = TeamSelections.Count(ts =>
            ts.EventRider.BikeClass == Enums.BikeClass.Class250 && ts.EventRider.IsAllStar);
        if (allStar250Count != 1)
        {
            errors.Add($"Team must have exactly 1 All-Star in 250 class. Current count: {allStar250Count}");
        }

        var allStar450Count = TeamSelections.Count(ts =>
            ts.EventRider.BikeClass == Enums.BikeClass.Class450 && ts.EventRider.IsAllStar);
        if (allStar450Count != 1)
        {
            errors.Add($"Team must have exactly 1 All-Star in 450 class. Current count: {allStar450Count}");
        }

        // Rule 5: No duplicate riders
        var distinctRiderIds = TeamSelections.Select(ts => ts.EventRider.RiderId).Distinct().Count();
        if (distinctRiderIds != TeamSelections.Count)
        {
            errors.Add("Team contains duplicate riders");
        }

        return (errors.Count == 0, errors);
    }

    /// <summary>
    /// Gets a summary string of the team composition.
    /// </summary>
    /// <returns>Human-readable team summary</returns>
    public string GetSummary()
    {
        var riders250 = TeamSelections
            .Where(ts => ts.EventRider.BikeClass == Enums.BikeClass.Class250)
            .Select(ts => $"{ts.EventRider.Rider.Name}{(ts.EventRider.IsAllStar ? " (AS)" : "")}")
            .ToList();

        var riders450 = TeamSelections
            .Where(ts => ts.EventRider.BikeClass == Enums.BikeClass.Class450)
            .Select(ts => $"{ts.EventRider.Rider.Name}{(ts.EventRider.IsAllStar ? " (AS)" : "")}")
            .ToList();

        var pointsText = TotalPoints.HasValue ? $" - {TotalPoints} points" : " (race not completed)";

        return $"250: {string.Join(", ", riders250)}\n" +
               $"450: {string.Join(", ", riders450)}\n" +
               $"Total{pointsText}";
    }
}
