// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulpMXFantasy.Infrastructure.Data;

#nullable disable

namespace PulpMXFantasy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117181322_AddRiderEligibilityFields")]
    partial class AddRiderEligibilityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("EventFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_format");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("LockoutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("series_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_events_event_date");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("ix_events_is_completed");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_events_slug");

                    b.HasIndex("EventDate", "IsCompleted")
                        .HasDatabaseName("ix_events_date_completed");

                    b.HasIndex("SeriesId", "RoundNumber")
                        .HasDatabaseName("ix_events_series_round");

                    b.ToTable("events", "domain");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.EventRider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BestQualyLapSeconds")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("best_qualy_lap_seconds");

                    b.Property<string>("BikeClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bike_class");

                    b.Property<int?>("CombinedQualyPosition")
                        .HasColumnType("integer")
                        .HasColumnName("combined_qualy_position");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int?>("FantasyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_points");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer")
                        .HasColumnName("finish_position");

                    b.Property<int>("Handicap")
                        .HasColumnType("integer")
                        .HasColumnName("handicap");

                    b.Property<int?>("HandicapAdjustedPosition")
                        .HasColumnType("integer")
                        .HasColumnName("handicap_adjusted_position");

                    b.Property<bool>("Ineligible")
                        .HasColumnType("boolean");

                    b.Property<string>("IneligibleReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsAllStar")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_star");

                    b.Property<bool>("IsInjured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_injured");

                    b.Property<decimal?>("PickTrend")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pick_trend");

                    b.Property<decimal?>("QualyGapToLeader")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("qualy_gap_to_leader");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rider_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BikeClass")
                        .HasDatabaseName("ix_event_riders_bike_class");

                    b.HasIndex("FinishPosition")
                        .HasDatabaseName("ix_event_riders_finish_position");

                    b.HasIndex("IsAllStar")
                        .HasDatabaseName("ix_event_riders_is_all_star");

                    b.HasIndex("RiderId");

                    b.HasIndex("EventId", "BikeClass")
                        .HasDatabaseName("ix_event_riders_event_class");

                    b.HasIndex("EventId", "FinishPosition")
                        .HasDatabaseName("ix_event_riders_event_finish");

                    b.HasIndex("EventId", "RiderId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_riders_event_rider_unique");

                    b.HasIndex("EventId", "BikeClass", "IsAllStar")
                        .HasDatabaseName("ix_event_riders_event_class_allstar");

                    b.ToTable("event_riders", "domain");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Rider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("PulpMxId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pulp_mx_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_riders_name");

                    b.HasIndex("PulpMxId")
                        .IsUnique()
                        .HasDatabaseName("ix_riders_pulp_mx_id");

                    b.ToTable("riders", "domain");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("series_type");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_series_is_active");

                    b.HasIndex("Year", "SeriesType")
                        .HasDatabaseName("ix_series_year_type");

                    b.ToTable("series", "domain");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsOptimized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_optimized");

                    b.Property<string>("TeamName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_name");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_teams_event_id");

                    b.HasIndex("IsOptimized")
                        .HasDatabaseName("ix_teams_is_optimized");

                    b.HasIndex("EventId", "TotalPoints")
                        .HasDatabaseName("ix_teams_event_points");

                    b.HasIndex("EventId", "UserId")
                        .HasDatabaseName("ix_teams_event_user");

                    b.ToTable("teams", "domain");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.TeamSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventRiderId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_rider_id");

                    b.Property<int?>("SelectionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("selection_order");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EventRiderId")
                        .HasDatabaseName("ix_team_selections_event_rider_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_selections_team_id");

                    b.HasIndex("TeamId", "EventRiderId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_selections_team_rider_unique");

                    b.ToTable("team_selections", "domain");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Event", b =>
                {
                    b.HasOne("PulpMXFantasy.Domain.Entities.Series", "Series")
                        .WithMany("Events")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.EventRider", b =>
                {
                    b.HasOne("PulpMXFantasy.Domain.Entities.Event", "Event")
                        .WithMany("EventRiders")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulpMXFantasy.Domain.Entities.Rider", "Rider")
                        .WithMany("EventRiders")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Team", b =>
                {
                    b.HasOne("PulpMXFantasy.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.TeamSelection", b =>
                {
                    b.HasOne("PulpMXFantasy.Domain.Entities.EventRider", "EventRider")
                        .WithMany()
                        .HasForeignKey("EventRiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulpMXFantasy.Domain.Entities.Team", "Team")
                        .WithMany("TeamSelections")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventRider");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventRiders");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Rider", b =>
                {
                    b.Navigation("EventRiders");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Series", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("PulpMXFantasy.Domain.Entities.Team", b =>
                {
                    b.Navigation("TeamSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
