// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulpMXFantasy.ReadModel;

#nullable disable

namespace PulpMXFantasy.ReadModel.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20260117034442_AddCommandProgressHistory")]
    partial class AddCommandProgressHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("read_model")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulpMXFantasy.Contracts.ReadModels.CommandProgressHistoryReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MilestoneName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("milestone_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("idx_progress_history_command");

                    b.ToTable("command_progress_history", "read_model");
                });

            modelBuilder.Entity("PulpMXFantasy.Contracts.ReadModels.CommandStatusReadModel", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("command_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ProgressMessage")
                        .HasColumnType("text")
                        .HasColumnName("progress_message");

                    b.Property<int?>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("ResultData")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_data");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("CommandId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_command_status_correlation");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_command_status_started");

                    b.HasIndex("CommandType", "Status")
                        .HasDatabaseName("idx_command_status_type");

                    b.ToTable("command_status", "read_model");
                });

            modelBuilder.Entity("PulpMXFantasy.Contracts.ReadModels.EventPredictionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BikeClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bike_class");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<float>("ExpectedPoints")
                        .HasColumnType("real")
                        .HasColumnName("expected_points");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("Handicap")
                        .HasColumnType("integer")
                        .HasColumnName("handicap");

                    b.Property<bool>("IsAllStar")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_star");

                    b.Property<float>("LowerBound")
                        .HasColumnType("real")
                        .HasColumnName("lower_bound");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<float>("PointsIfQualifies")
                        .HasColumnType("real");

                    b.Property<int?>("PredictedFinish")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_finish");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rider_id");

                    b.Property<string>("RiderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rider_name");

                    b.Property<int>("RiderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("rider_number");

                    b.Property<float>("UpperBound")
                        .HasColumnType("real")
                        .HasColumnName("upper_bound");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("idx_event_predictions_event");

                    b.HasIndex("EventId", "BikeClass")
                        .HasDatabaseName("idx_event_predictions_class");

                    b.HasIndex("EventId", "ExpectedPoints")
                        .HasDatabaseName("idx_event_predictions_points");

                    b.HasIndex("EventId", "RiderId")
                        .IsUnique()
                        .HasDatabaseName("uq_event_predictions_event_rider");

                    b.ToTable("event_predictions", "read_model");
                });

            modelBuilder.Entity("PulpMXFantasy.Contracts.ReadModels.EventReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("LockoutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RiderCount")
                        .HasColumnType("integer")
                        .HasColumnName("rider_count");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("series_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("idx_events_date");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_events_slug");

                    b.HasIndex("IsCompleted", "EventDate")
                        .HasDatabaseName("idx_events_upcoming");

                    b.ToTable("events", "read_model");
                });

            modelBuilder.Entity("PulpMXFantasy.Contracts.ReadModels.ModelMetadataReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BikeClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bike_class");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<float?>("MeanAbsoluteError")
                        .HasColumnType("real")
                        .HasColumnName("mean_absolute_error");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_path");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_type");

                    b.Property<float?>("RSquared")
                        .HasColumnType("real")
                        .HasColumnName("r_squared");

                    b.Property<DateTimeOffset>("TrainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trained_at");

                    b.Property<int>("TrainingSamples")
                        .HasColumnType("integer")
                        .HasColumnName("training_samples");

                    b.Property<float?>("ValidationAccuracy")
                        .HasColumnType("real")
                        .HasColumnName("validation_accuracy");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TrainedAt")
                        .HasDatabaseName("idx_model_metadata_trained");

                    b.HasIndex("BikeClass", "ModelType", "IsActive")
                        .HasDatabaseName("idx_model_metadata_active");

                    b.HasIndex("BikeClass", "ModelType", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_model_metadata_version");

                    b.ToTable("model_metadata", "read_model");
                });
#pragma warning restore 612, 618
        }
    }
}
