using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PulpMXFantasy.Domain.Entities;

namespace PulpMXFantasy.Infrastructure.Data.Configurations;

/// <summary>
/// Entity Type Configuration for Team entity.
/// </summary>
/// <remarks>
/// TEAM TABLE STRUCTURE:
/// =====================
/// Configures the fantasy teams table:
/// - Team identification (UserId, TeamName)
/// - Event linkage (EventId)
/// - Scoring (TotalPoints - calculated after race)
/// - Source (IsOptimized - ML-generated vs manual)
/// - Relationships (8 TeamSelections)
///
/// BUSINESS RULES:
/// ===============
/// - Each team belongs to one event
/// - Each team has exactly 8 riders (4 from 250, 4 from 450)
/// - Exactly 1 All-Star per class required
/// - TotalPoints calculated after race completion
///
/// MULTIPLAYER COMPETITION:
/// ========================
/// Multiple users create teams for same event:
/// - Leaderboard ranks teams by TotalPoints (highest wins)
/// - Users compete to pick optimal 8-rider combination
///
/// INDEXING STRATEGY:
/// ==================
/// - Composite index on (EventId, UserId) for "user's team for event" lookup
/// - Index on EventId for leaderboard queries (all teams for an event)
/// - Index on TotalPoints for sorting leaderboards
/// - Index on IsOptimized for ML performance tracking
/// </remarks>
public class TeamConfiguration : IEntityTypeConfiguration<Team>
{
    public void Configure(EntityTypeBuilder<Team> builder)
    {
        // ==============================================================
        // TABLE AND PRIMARY KEY
        // ==============================================================

        builder.ToTable("teams");

        builder.HasKey(t => t.Id);

        // ==============================================================
        // COLUMNS
        // ==============================================================

        builder.Property(t => t.Id)
            .HasColumnName("id")
            .IsRequired();

        builder.Property(t => t.EventId)
            .HasColumnName("event_id")
            .IsRequired();

        // UserId: String identifier for team owner
        // Future: Could be foreign key to AspNetUsers table
        builder.Property(t => t.UserId)
            .HasColumnName("user_id")
            .HasMaxLength(100)
            .IsRequired();

        // TeamName: Optional custom name
        builder.Property(t => t.TeamName)
            .HasColumnName("team_name")
            .HasMaxLength(200);

        // TotalPoints: Calculated after race completion
        // Sum of all 8 riders' fantasy points
        // NULL until race completes and Team.CalculateTotalScore() is called
        builder.Property(t => t.TotalPoints)
            .HasColumnName("total_points");

        // IsOptimized: Was this team generated by ML optimizer?
        builder.Property(t => t.IsOptimized)
            .HasColumnName("is_optimized")
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(t => t.CreatedAt)
            .HasColumnName("created_at")
            .IsRequired();

        builder.Property(t => t.UpdatedAt)
            .HasColumnName("updated_at")
            .IsRequired();

        // ==============================================================
        // INDEXES
        // ==============================================================

        // Composite index on (EventId, UserId) for "user's team for event" lookup
        // Query pattern: WHERE event_id = @EventId AND user_id = @UserId
        // Common use case: Show user their team for current event
        builder.HasIndex(t => new { t.EventId, t.UserId })
            .HasDatabaseName("ix_teams_event_user");

        // Index on EventId for leaderboard queries
        // Query pattern: WHERE event_id = @EventId ORDER BY total_points DESC
        // Use case: Display all teams for an event (leaderboard)
        builder.HasIndex(t => t.EventId)
            .HasDatabaseName("ix_teams_event_id");

        // Composite index on (EventId, TotalPoints) for efficient leaderboard sorting
        // Query pattern: WHERE event_id = @EventId ORDER BY total_points DESC LIMIT 100
        // Most common query for leaderboards
        builder.HasIndex(t => new { t.EventId, t.TotalPoints })
            .HasDatabaseName("ix_teams_event_points");

        // Index on IsOptimized for ML performance tracking
        // Query pattern: WHERE is_optimized = true
        // Use case: Analyze ML-generated team performance vs human selections
        builder.HasIndex(t => t.IsOptimized)
            .HasDatabaseName("ix_teams_is_optimized");

        // ==============================================================
        // RELATIONSHIPS
        // ==============================================================

        // Many Teams -> One Event (team belongs to one event)
        builder.HasOne(t => t.Event)
            .WithMany() // No inverse navigation on Event
            .HasForeignKey(t => t.EventId)
            .OnDelete(DeleteBehavior.Cascade); // If event deleted, delete all teams

        // One Team -> Many TeamSelections (exactly 8 riders per team)
        builder.HasMany(t => t.TeamSelections)
            .WithOne(ts => ts.Team)
            .HasForeignKey(ts => ts.TeamId)
            .OnDelete(DeleteBehavior.Cascade); // If team deleted, delete all rider selections
    }
}
